version: "3"
services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.prod
    tty: true
    environment:
      - CGO_ENABLED=0
    ports:
      - 443:443
    volumes:
      - .:/app
      - ./logs/backend:/.logs

  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "80:80"
      stdin_open: true
      tty: true
      volumes:
        - ./nginx/src:/src
