version: "3"
services:
  app:
    build: ./backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src/github.com/kikils/go-websocket

  frontend:
      build: ./frontend
      ports:
        - "8000:8000"
      stdin_open: true
      tty: true
      environment:
        - CHOKIDAR_USEPOLLING=true
      volumes:
        - ./frontend/src:/src