version: "3"
services:
  app:
    build: ./backend
    tty: true
    ports:
      - 443:443
    environment:
      - CGO_ENABLED=0
    volumes:
      - ./backend:/go/src/github.com/kikils/go-websocket

  frontend:
      build: ./frontend
      ports:
        - "8000:8000"
      stdin_open: true
      tty: true
      command: "yarn dev"
      environment:
        - CHOKIDAR_USEPOLLING=true
        - API_URL=0.0.0.0:443
      volumes:
        - ./frontend/src:/src