version: "3"
services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src/github.com/kikils/go-websocket

  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - "80:80"
      stdin_open: true
      tty: true
      volumes:
        - ./nginx/src:/src
