name: Build and Push ng-word-game to to Dev Environment

on:
  push:
    branches:
      - support/setup-github-actions

jobs:
  build-and-push-to-gcr:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    strategy:
      matrix:
        include:
        - dockerfile-path: build/Dockerfile.backend
          dockerimage: gcr.io/ng-word-game-dev/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: 'ng-word-game-dev'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          create_credentials_file: true
          access_token_lifetime: 900s
          workload_identity_provider: projects/888272509388/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
          service_account: 'github-actions@ng-word-game-dev.iam.gserviceaccount.com'

      - name: Login to GCR
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker -q

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.dockerimage }}
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile-path }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-dev-cluster:
    permissions:
      contents: read
      id-token: write
    needs: build-and-push-to-gcr
    name: Deploy ng-word-game to to Dev Environment
    runs-on: ubuntu-latest

    steps:
      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: 'ng-word-game-dev'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          access_token_lifetime: 900s
          workload_identity_provider: projects/888272509388/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
          service_account: 'github-actions@ng-word-game-dev.iam.gserviceaccount.com'

      - name: Login with gcloud
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud container clusters get-credentials ng-word-game --region asia-east1
      - name: Deploy
        run: |
          kubectl set image -n ng-word-game-api --record deployment/ng-word-game-api ng-word-game-api=${{ needs.build-and-push-to-gcr.outputs.image }}
          kubectl rollout status -n ng-word-game-api deployment/ng-word-game-api
